name: publishToFtp

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sebastianpopp/ftp-action@releases/v2
    with:
      host: ${{ secrets.FTP_SERVER }}
      user: ${{ secrets.FTP_USER }}
      password: ${{ secrets.FTP_PASS }}
      localDir: "loginpage"