name: publishToFtp

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP_Upload
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        localDir: "loginpage"
        remoteDir: "html"
    - name: Set_permissions
      uses: fifsky/ssh-action@master
      with:
        command: |
          chown -R pi:www-data /home/pi/html
          find /home/pi/html/ -type f -exec chmod 664 {} +
          find /home/pi/html/ -type d -exec chmod 775 {} +
          chmod +x /home/pi/html/*.py
        host: ${{ secrets.FTP_SERVER }}
        pass: ${{ secrets.SSH_PASS}}
